apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc
  labels:
    app: fastapi-helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: fastapi-helloworld