apiVersion: v1
kind: Service
metadata:
  name: argocd-svc
  labels:
    app: argocd-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: argocd-ui